### ISSUE TITLE
ZX Spectrum request

### ISSUE THREAD

**Issue by bmnicolae** [lipebello/es-theme-Retrorama#3]
Phill thank you for you hard work.
I'm from Europe and in my childhood I've played a lot of games on [ZX Spectrum](https://en.wikipedia.org/wiki/ZX_Spectrum). 
When do you have the time can you support it?

Thank you very much!

**Comment by lipebello** [comment]
Hi, thanks a lot!
Sure thing! i'll include it on my next update

**Comment by lipebello** [comment]
Hello, Zx spectrum added on 1.8
