### ISSUE TITLE
Amiga Theme Request

### ISSUE THREAD

**Issue by schmitzCatz** [lipebello/es-theme-Retrorama#5]
Hi,

First of all thank you for all the hard work you put into this piece of art! I'm enjoying it a lot with my new retropie bartop.  Any change of adding a themes for [Amiga](https://en.wikipedia.org/wiki/Amiga) in any of the future updates? That would be realy nice.

Keep up the good work.

Cheers,

Oliver

**Comment by lipebello** [comment]
Hi, thanks a lot!
Sure thing. Amiga is almost ready and i'll be adding it on the next update.

**Comment by schmitzCatz** [comment]
Great! Thanks a lot! :-)

**Comment by lipebello** [comment]
Hello, Amiga added on version 1.8.
