### ISSUE TITLE
Text cutting off

### ISSUE THREAD

**Issue by EmeraldaChaos** [lipebello/es-theme-retrorama#8]
For me, the text cuts off at the bottom of my game list with half of the title showing up or even less. I don't know if this is something that can be fixed on my end or not. All I know is it doesn't happen in Game and Watch but does happen for every other console as far as I can tell.

**Comment by not-well** [comment]
I've noticed that this happens in all black and white theme and in Game and Watch, but I've seen it on the computer. I'm going to do other tests on the tv and try to fix it. Lets the guy worry just about the drawings.
![captura de tela de 2018-12-18 13-25-58](https://user-images.githubusercontent.com/26507463/50168570-7fa9e200-02ca-11e9-9621-06709df1719a.png)
![captura de tela de 2018-12-18 13-26-11](https://user-images.githubusercontent.com/26507463/50168602-8d5f6780-02ca-11e9-8f1b-d1d1d7cf519a.png)

**Comment by EmeraldaChaos** [comment]
Thanks for the help! Tell me what you find when you do so this can hopefully be fixed!

**Comment by EmeraldaChaos** [comment]
I actually fixed it, you just need to download these files and replace some files with these ones [https://www.dropbox.com/s/z6g1smcjz9zcbpm/Retrorama%20fix.rar?dl=0](url)

**Comment by not-well** [comment]
I still had not tried. So as the problem has already been solved it's time to close the issue.
